This document is a current working draft of the System Structure and Parameterization Standard (SSP).
*It is unreleased, and does not constitute a standard of the Modelica Association.*

// On the Downloads page (https://ssp-standard.org/downloads), this specification, as well as supporting XML schema files are provided.

Contact the SSP development group at map-ssp_projectlead@googlegroups.com.

<<<

History / Road Map

[width="100%",cols="18%,12%,70%",]
|===
|Version |Date |Remarks
|1.0 |2019-03-05 |First Public Release of SSP
|1.0.1 |2022-07-25 |Public Release of SSP 1.0.1
|===

Please report issues that you find with this specification to map-ssp_projectlead@googlegroups.com.

<<<

*License of this document*

Copyright © 2016 – 2024 Modelica Association Project “SSP”

This document is provided “as is” without any warranty.
It is licensed under the CC-BY-SA (Creative Commons Attribution-Sharealike 4.0 International) license, which is the license used by Wikipedia.
The human-readable summary of the license text from http://creativecommons.org/licenses/by-sa/4.0/ is as follows:

You are free to:

____
*Share* — copy and redistribute the material in any medium or format

*Remix* — remix, transform, and build upon the material for any purpose, even commercially.

The licensor cannot revoke these freedoms as long as you follow the license terms.
____

Under the following terms:

____
*Attribution* — You must give appropriate credit, provide a link to the license, and indicate if changes were made.
You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.

*Share Alike* — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original.
____

The legal license text and disclaimer is available at:

http://creativecommons.org/licenses/by-sa/4.0/legalcode

*Note:*

____
Article (3a) of this license requires that modifications of this work must clearly label, demarcate or otherwise identify that changes were made.

The XML schema files that accompany this document are available under the BSD 2-Clause license (https://opensource.org/license/bsd-2-clause/).

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights.
Modelica Association shall not be held responsible for identifying such patent rights.

If you have improvement suggestions, please send them to the SSP development group at map-ssp_projectlead@googlegroups.com.
____

<<<

*Abstract*

This document defines the SSP standard as a tool-independent format for the description, packaging and exchange of system structures and their parameterization.
The standard is comprised of a set of XML-based formats to describe a network of component models with their signal flow and parametrization, as well as a ZIP-based packaging format for efficient distribution of entire systems, including any referenced models and other resources.

<<<

*About SSP*

*Conventions used in this Document*

* The key words *MUST*, *MUST NOT*, *REQUIRED*, *SHALL*, *SHALL NOT*, *SHOULD*, *SHOULD NOT*, *RECOMMENDED*, *MAY*, and *OPTIONAL* in this document are to be interpreted as described in RFC 2119 [RFC2119].
* Non-normative text is given in square brackets in italic font: [ _especially examples are defined in this style._ ].

= What is new in SSP 2.0
The SSP development group has provided this update to the SSP standard in reaction to the release of FMI 3.0 as well as to new end user requirements. 
Even though SSP 2.0 is seen as a major version update, SSP 1.0 artifacts are still seen as fully compliant to the SSP 2.0 release. Naturally, however, SSP 2.0 compliant artifacts are not necesarali compliant to the SSP 1.0 schema.

The SSP 2.0 release is primarily focused on supporting the updates of FMI 3.0; however, a number of minor but significant changes related to supporting, for example, incremental development as well non-fmi components are introduced. An overview of the changes are provided in the two bulleted lists below: the first aggregating features related to FMI 3.0 and the second to non-FMI related new requirements. 
Many different advancements to the specification have been discussed; however, the SSP 2.0 specification has been deduced as a least-common denominator for the exchange of simulation packages that is able to provide value for both end-users and tool suppliers. 

== FMI 3.0 related updates
* Basic types, such as Float32.
* Scheduled execution (component implementation attribute).
* Clocked signals. 
* Arrays. Support for expressing arrays in connectors in the SSD as well as in the SSV and SSB. 
* The expression of annotations are aligned to that of FMI 3.0 and SSP Traceability. 

== Non-FMI 3.0 related updates
* Optional inner view connector coordinates. This feature enables more advanced graphical editing of SSP models. 
* Initial meta-data support from "SSP Traceability" project. First step in aligning SSP with SSP Traceability. Allows the end user to capture, for example, life-cycle information in the SSP package.
* Optional support for representing Modelica components and connectors in SSP. SSP is not FMI exclusive and SSP now nativly supports Modelica models as components.
* The component source is made optional to support the usage of system structure descriptions for simulation architecture design without available component implementations. Furthermore, connectors with kind="local" are added to the specification. This, for example, further enriches SSP for architecting purposes.
* General clarifications and bug fixes.
* Constant and structuralParameter are added as allowed connector kinds. This expansion further aligns SSP 2.0 to FMI and its constructs. 

