== Common Content (SSC) [[SSC]]

Common Structures and Attributes that are used across all XML Schemas are defined in the SystemStructureCommon.xsd Schema, which is imported by all other XML Schemas.
All Types and AttributeGroups live in the `http://ssp-standard.org/SSP1/SystemStructureCommon` namespace, nicknamed `ssc`.

=== Common Attributes

All XML elements that correspond to an entity of the system model will have the following set of common XML attributes, as defined in the ssc:ABaseElement attribute group:

image:images/SystemStructureCommon_ABaseElement.svg[image]

[width="100%",cols="18%,82%",options="header",]
|===
|Attribute |Description
|id |This optional attribute gives the model entity a file-wide unique id which can be referenced from other entities or via URI fragment identifier.
|description |This optional attribute gives a human readable longer description of the model entity, which can be shown to the user where appropriate.
|===

=== Common XML Child Elements

All XML elements that correspond to an entity of the system model will have the following set of common child elements:

image:images/SystemStructureCommon_TAnnotations.svg[image]

[width="100%",cols="18%,82%",options="header",]
|===
|Element |Description
|Annotations |This optional element can be used to give additional information for any model entity.
When it is present, it *MUST* contain 1 or more Annotation elements as specified below.
|===

Each annotation is encapsulated in an Annotation element, with a required type attribute specifying the type of the annotation, and arbitrary XML content from arbitrary namespaces.

image:images/SystemStructureCommon_Annotation.svg[image]
    
In order to ensure uniqueness the annotation type *SHOULD* be provided in reverse domain name notation [ _cf.
Java package names or Apple UTIs_ ] of a domain that is controlled by the entity defining the semantics and content of the annotation.
For vendor-specific annotations this *SHOULD* be a domain controlled by the tool vendor.
For MAP-SSP-defined annotations, this *MUST* be a domain under the org.modelica or org.ssp-standard prefixes.
Annotations that are not defined by MAP SSP *MUST NOT* use these two prefixes,

This mechanism can be used both for tool-specific annotations, as well as for layered standards (see <<Versioning and Layered Standards>>) and other agreed-upon extensions, and thus provides a generic extension mechanism.

=== Top-Level Attributes

Top-level attributes are optional meta-data attributes common to all top-level container elements of all defined file formats.

image:images/SystemStructureCommon_ATopLevelMetaData.svg[image]

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description
|author |Optional attribute giving the name and/or organization of the author of the contents of this file.
|fileversion |Optional attribute giving the version of the contents of this file.
|copyright |Optional attribute giving information about copyrights of the contents of this file.
|license |Optional attribute giving information about licensing of the contents of this file.
|generationTool |Optional attribute giving information about the tool used to generate this file.
|generationDateAndTime |Optional attribute giving the date and time this file was generated.
|===

=== Top-Level XML Child Elements

Top-level elements of a defined file format may have the following set of common child elements.

By design, the enumeration and unit definitions for each file are included in that file directly (i.e. enumeration and unit definitions are file scoped).
This is intended to ensure the separate portability of individual files, with each file containing a self-consistent set of information.
When processing information from multiple files, either from the same or separate system structures, it is up to the importing implementation to deal with any inconsistencies between files found.

==== Enumerations

image:images/SystemStructureCommon_TEnumerations.svg[image]

This optional element *MUST* contain definitions for all enumerations referenced in a file.

{empty}[ _As a file-based interchange standard, the natural scope for units and enumerations is the file scope, so that files can be parsed and processed separately, without the need for cross-file references or scoped references with the possibilities of shadowing and ambiguities._
_Upon import tools are free to merge unit information across files or separate them between hierarchy layers as they see fit._ ]

image:images/SystemStructureCommon_Enumeration.svg[image]

Each enumeration is defined through an Enumeration XML element:

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description
|name |This required attribute provides a name, which *MUST* be unique within the set of enumerations in a given file.
|===

The following XML child elements are specified for the Enumeration element:

[width="100%",cols="18%,82%",options="header",]
|===
|Element |Description
|Item |One or more elements specifying the items of the enumeration.
|===

===== Item

image:images/SystemStructureCommon_Item.svg[image]

For each item in the enumeration there is one Item XML element with the following attributes:

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description
|name |This required attribute provides a name for the enumeration item.
|value |This required attribute provides a value for the enumeration item.
|===

==== Units

image:images/SystemStructureCommon_TUnits.svg[image]

This optional element *MUST* contain definitions for all units referenced in a file.

{empty}[ _As a file-based interchange standard, the natural scope for units and enumerations is the file scope, so that files can be parsed and processed separately, without the need for cross-file references or scoped references with the possibilities of shadowing and ambiguities._
_Upon import tools are free to merge unit information across files or separate them between hierarchy layers as they see fit._ ]

image:images/SystemStructureCommon_Unit.svg[image]

Each unit is defined through a Unit XML element:

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description
|name |This required attribute provides a name, which *MUST* be unique within the set of units in a given file.
|===

The following XML child elements are specified for the Unit element:

[width="100%",cols="18%,82%",options="header",]
|===
|Element |Description
|BaseUnit |Required element defining the base unit of the given unit in SI units, see below.
|===

===== BaseUnit

This element defines the base unit of the given unit in SI units.
This is completely aligned with the specification of base units in section 2.4.3 of the FMI 3.0 standard [<<FMI30>>] and section 2.2.2 of the FMI 2.0 standard [<<FMI20>>].

image:images/SystemStructureCommon_BaseUnit.svg[image]

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description
|kg |Optional attribute specifying the exponent of SI base unit kg, defaults to 0.
|m |Optional attribute specifying the exponent of SI base unit m, defaults to 0.
|s |Optional attribute specifying the exponent of SI base unit s, defaults to 0.
|A |Optional attribute specifying the exponent of SI base unit A, defaults to 0.
|K |Optional attribute specifying the exponent of SI base unit K, defaults to 0.
|mol |Optional attribute specifying the exponent of SI base unit mol, defaults to 0.
|cd |Optional attribute specifying the exponent of SI base unit cd, defaults to 0.
|rad |Optional attribute specifying the exponent of SI base unit rad, defaults to 0.
|factor |Optional attribute specifying an optional factor, defaults to 1.
|offset |Optional attribute specifying an optional offset, defaults to 0.
|===

=== XML Element Groups

These XML element choices and sequences are common to multiple file formats.
They are used inside elements to select one of multiple child elements, or provide common sequence content.

[#ssc_types]
==== Type Choice

image:images/SystemStructureCommon_GTypeChoice.svg[image]

The following XML child elements denote the data type of a connector or dictionary entry.
[ _Note that in the case of connectors the use of a type element itself is optional, in the case of dictionary entries it is required_ ].

[width="100%",cols="33%,67%",options="header",]
|===
|Element |Description
|Real / Float64 / Float32 / +
Integer / Int8 / UInt8 / Int16 / UInt16 / +
Int32 / UInt32 / Int64 / UInt64 / +
Boolean / String / Enumeration / Binary / Clock |Exactly one of these elements *MUST* be present to specify the type of the element.
See below for details.
|===

===== Real

image:images/SystemStructureCommon_Real.svg[image]

This type specifies that the connector in question represents an IEEE754 double precision floating point number.

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description
|unit |This optional attribute gives the name of a unit.
The name *MUST* match the name of a Unit entry in the Units XML element of the top-level element of the file.

If the attribute is not supplied, the unit is determined through default mechanisms:
For FMU components, the unit of the underlying variable would be used, or no unit, if no unit is specified.
For systems, the units of connected underlying connectors could be used if unambiguous.

If a unit (or its absence) cannot be deduced unambinguously, the user should be informed of this error.

Notwithstanding these mechanisms, unitless variables of type Real are supported.
|===

===== Float64

image:images/SystemStructureCommon_Float64.svg[image]

This type specifies that the connector in question represents an IEEE754 double precision floating point number.

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description
|unit |This optional attribute gives the name of a unit.
The name *MUST* match the name of a Unit entry in the Units XML element of the top-level element of the file.

If the attribute is not supplied, the unit is determined through default mechanisms:
For FMU components, the unit of the underlying variable would be used, or no unit, if no unit is specified.
For systems, the units of connected underlying connectors could be used if unambiguous.

If a unit (or its absence) cannot be deduced unambinguously, the user should be informed of this error.

Notwithstanding these mechanisms, unitless variables of type Float64 are supported.
|===

===== Float32

image:images/SystemStructureCommon_Float32.svg[image]

This type specifies that the connector in question represents an IEEE754 single precision floating point number.

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description
|unit |This optional attribute gives the name of a unit.
The name *MUST* match the name of a Unit entry in the Units XML element of the top-level element of the file.

If the attribute is not supplied, the unit is determined through default mechanisms:
For FMU components, the unit of the underlying variable would be used, or no unit, if no unit is specified.
For systems, the units of connected underlying connectors could be used if unambiguous.

If a unit (or its absence) cannot be deduced unambinguously, the user should be informed of this error.

Notwithstanding these mechanisms, unitless variables of type Float32 are supported.
|===

===== Integer

image:images/SystemStructureCommon_Integer.svg[image]

This type specifies that the connector in question represents a 32-bit signed integer number.

===== Int8

image:images/SystemStructureCommon_Int8.svg[image]

This type specifies that the connector in question represents a 8-bit signed integer number.

===== UInt8

image:images/SystemStructureCommon_UInt8.svg[image]

This type specifies that the connector in question represents a 8-bit unsigned integer number.

===== Int16

image:images/SystemStructureCommon_Int16.svg[image]

This type specifies that the connector in question represents a 16-bit signed integer number.

===== UInt16

image:images/SystemStructureCommon_UInt16.svg[image]

This type specifies that the connector in question represents a 16-bit unsigned integer number.

===== Int32

image:images/SystemStructureCommon_Int32.svg[image]

This type specifies that the connector in question represents a 32-bit signed integer number.

===== UInt32

image:images/SystemStructureCommon_UInt32.svg[image]

This type specifies that the connector in question represents a 32-bit unsigned integer number.

===== Int64

image:images/SystemStructureCommon_Int64.svg[image]

This type specifies that the connector in question represents a 64-bit signed integer number.

===== UInt64

image:images/SystemStructureCommon_UInt64.svg[image]

This type specifies that the connector in question represents a 64-bit unsigned integer number.

===== Boolean

image:images/SystemStructureCommon_Boolean.svg[image]

This type specifies that the connector in question represents a Boolean value.

===== String

image:images/SystemStructureCommon_String.svg[image]

This type specifies that the connector in question represents a zero-terminated UTF-8 encoded string.

===== Enumeration

image:images/SystemStructureCommon_GTypeChoice_Enumeration.svg[image]

This type specifies that the connector in question represents an enumeration value, as specified by the enumeration definition.
The underlying type of the connector is the same as for Integer.

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description
|name |This required attribute gives the name of an enumeration which references into the defined enumerations of a document.
The name *MUST* match the name of an Enumeration entry in the Enumerations XML element of the top-level element of the file.
|===

===== Binary

image:images/SystemStructureCommon_Binary.svg[image]

This type specifies that the connector in question represents a length-terminated binary data type, like the binary type defined for the FMI 3.0 standard, or substitute types like the binary type defined via the OSI Sensor Model Packaging specification [<<OSMP150>>].

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description
|mime-type a|
This optional attribute specifies the MIME type of the underlying binary data, which defaults to the non-specific application/octet-stream type.
This information *CAN* be used by the implementation to detect mismatches between connected binary connectors, or provide automatic means of conversion between different formats.
It should be noted that the implementation is *not required* to provide this service, i.e. it remains the responsibility of the operator to ensure only compatible binary connectors are connected.

The attribute value *MUST* be a valid MIME type as specified in RFC 2045; it *CAN* include additional arguments, etc., as specified in RFC 2045.
|===

===== Clock

image:images/SystemStructureCommon_Clock.svg[image]

This type specifies that the connector represents a clock signal, compatible with the clock type defined in the FMI 3.0 standard.
For detailed clock semantics and behavior, refer to the FMI 3.0 specification.

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description

|intervalVariability
a|This optional attribute specifies the interval variability of the clock signal.
Valid values are: `constant`, `fixed`, `tunable`, `changing`, `countdown`, `triggered`.

|intervalDecimal
a|This optional attribute specifies the clock interval in seconds as a floating-point value.

|shiftDecimal
a|This optional attribute specifies the time offset in seconds for the first clock tick relative to simulation start.
Default is 0.

|supportsFraction
a|This optional boolean attribute indicates whether the clock supports fractional representations for intervals and shifts.
Default is `false`.

|resolution
a|This optional attribute specifies the denominator for rational number representations of intervals and shifts.

|intervalCounter
a|This optional attribute specifies the numerator of the clock interval as rational number (intervalCounter / resolution).

|shiftCounter
a|This optional attribute specifies the numerator of the clock shift as rational number (shiftCounter / resolution).
Default is 0.

|priority
a|This optional attribute specifies the execution priority of the clock for scheduling purposes.
Lower values indicate higher priority.
|===

[#ssc_transformations]
==== Transformation Choice

image:images/SystemStructureCommon_GTransformationChoice.svg[image]

The following XML child elements specify a transformation to be applied to a value prior to its use in a connection or parameter mapping:

[width="100%",cols="42%,58%",options="header",]
|===
|Element |Description
|LinearTransformation |Specifies a linear transformation to be performed on the connection values.
|BooleanMappingTransformation |Specifies a boolean mapping transformation to be performed on the connection values.
|IntegerMappingTransformation |Specifies an integer mapping transformation to be performed on the connection values.
|EnumerationMappingTransformation |Specifies an enumeration mapping transformation to be performed on the connection values.
|===

===== LinearTransformation

image:images/SystemStructureCommon_LinearTransformation.svg[image]

This element provides for a linear transformation of the source value to the target value, i.e. in the calculation target = factor * source + offset.

Note that conversions based on different units are performed, unless prevented by suppressUnitConversion, prior to the application of the linear transformation, i.e. the value of source is already converted to the target unit in the formula above.
Linear transformations are only valid for connectors of Real, Float64 or Float32 type.

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description
|factor |This attribute specifies an optional factor value to use in a linear transformation.
The default is 1.
|offset |This attribute specifies an optional offset value to use in a transformation.
The default is 0.
|===

===== BooleanMappingTransformation

image:images/SystemStructureCommon_BooleanMappingTransformation.svg[image]

This element provides for a transformation of Boolean values based on a mapping table and is valid for connectors of Boolean type.
Each mapping table entry is provided by a MapEntry element.
Mapping entries *MUST* be unambiguous, i.e. for a given source value at a maximum one entry specifying that source value *MUST* be present.
The mapping does not have to be complete, i.e. partial mappings *CAN* be specified.
In that case values not mapped by a mapping entry are kept unchanged.

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description
|source |This attribute gives the source value that this entry applies to.
|target |This attribute gives the value to use instead of the source value when applying it to the system or component.
|===

===== IntegerMappingTransformation

image:images/SystemStructureCommon_IntegerMappingTransformation.svg[image]

This element provides for a transformation of integer values based on a mapping table and is valid for connectors of all the integer types and Enumeration type.
Each mapping table entry is provided by a MapEntry element.
Mapping entries *MUST* be unambiguous, i.e. for a given source value at a maximum one entry specifying that source value *MUST* be present.
The mapping does not have to be complete, i.e. partial mappings *CAN* be specified.
In that case values not mapped by a mapping entry are kept unchanged.

When mapping to an Enumeration type, the target value *MUST* be a valid enumeration value for that type.
When mapping from an Enumeration type, the source value *MUST* be a valid enumeration value for that type.
This transformation can be applied between connectors of different Enumeration types, as long as all resulting target values are valid in the target Enumeration type.

The target values provided in transformation entries *MUST* be limited to the value space of the target connector.
The source values provided in transformation entries *CAN* exceed the value space of the source connector.
Such entries are ignored in the mapping process.

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description
|source |This attribute gives the source value that this entry applies to.
|target |This attribute gives the value to use instead of the source value when applying it to the system or component.
|===

===== EnumerationMappingTransformation

image:images/SystemStructureCommon_EnumerationMappingTransformation.svg[image]

This element provides for a transformation of enumeration values based on a mapping table of their enumeration item names and is valid for connectors of Enumeration type.
Each mapping table entry is provided by a MapEntry element.
Mapping entries *MUST* be unambiguous, i.e. for a given source value at a maximum one entry specifying that source value *MUST* be present.
The mapping does not have to be complete, i.e. partial mappings *CAN* be specified.
In that case values not mapped by a mapping entry are kept unchanged.

When mapping to an Enumeration type, the target value *MUST* be a valid enumeration value for that type.
When mapping from an Enumeration type, the source value *MUST* be a valid enumeration value for that type.
This transformation can be applied between connectors of different Enumeration types, as long as all resulting target values are valid in the target Enumeration type.

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description
|source |This attribute gives the source value that this entry applies to.
|target |This attribute gives the value to use instead of the source value when applying it to the system or component.
|===

[#ssc_dimensions]
==== Dimension Sequence

image:images/SystemStructureCommon_GDimensions.svg[image]

The Dimension element is used to specify the dimensions of array connectors, signal dictionary entries, or parameter values.

[width="100%",cols="33%,67%",options="header",]
|===
|Element |Description
|Dimension |One or more instances of this element *CAN* be present to specify the dimensions of the containing model element.
If no instances are present, the containing model element is scalar.
See below for details.
|===

===== Dimension

image:images/SystemStructureCommon_Dimension.svg[image]

This element specifies one dimension of a potentially multi-dimensional array connector, signal dictionary entry, or parameter value (modeling element).
If no dimension elements are present in a modeling element, it is a scalar modeling element.
The number of dimension elements in a modeling element provides the dimensionality of the array.

For connector elements, either the size or the sizeConnector attributes *CAN* be present on the element, indicating a fixed size, or a size that depends on the structural parameter or constant referenced by the sizeConnector attribute.
If none of the attributes are present, then the size of the dimension is unspecified at the SSD level.
It is considered an error if both attributes are present.

For signal dictionary and parameter value elements, only the size attribute can be used and therefore *MUST* be present on the element, indicating a fixed size.
For those elements, it is considered an error if the sizeConnector attribute is present.

The following XML attributes are specified for the Dimension element:

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description
|size a|
This attribute gives the size of this dimension of the array as a fixed, unchangeable number.
|sizeConnector a|
This attribute references another connector by name, that gives the size of this dimension of the array connector, e.g. a structural parameter or a constant of the underlying component that gives the dimension size.
|===

{empty}[ _SSP uses `size` where FMI uses `start` because SSP specifies structural dimension extents directly._ ]

[#ssc_metadata]
==== MetaData Sequence

image:images/SystemStructureCommon_GMetaData.svg[image]

The group GMetaData allows the specification of additional meta data for a given model element.
Multiple (or no) MetaData elements may be present in a given model element.

[width="100%",cols="33%,67%",options="header",]
|===
|Element   |Description
|MetaData  |One or more instances of this element *CAN* be present to specify meta data related to the containing model element.
See below for details.
|===

===== MetaData

image:images/SystemStructureCommon_MetaData.svg[image]

This element specifies a source of meta data related to the containing model element.

The MetaData element is structured by the following subordinated elements.

[width="100%",cols="33%,67%",options="header",]
|===
|Element  |Description
|Content  |An instance of this element *CAN* be present to contain inlined content of the model element meta data.
If it is present, then the attribute `source` of the MetaData element *MUST NOT* be present.
See below for details.
|Signature|One or more instances of this element *CAN* be present to specify digital signature information on the meta data referenced by the enclosing MetaData element.
It is left unspecified what types of signatures are used and/or available for now.
See below for details.
|===

The following XML attributes are specified for the MetaData element:

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description
|kind a|
This attribute indicates the kind of model element meta data that is referenced, i.e. what role it plays in relation to the model element being described.
The kind can be `general` or `quality`, indicating general meta data or quality related meta data, respectively.
|type a|
This mandatory attribute specifies the MIME type of the meta data, which does not have a default value.
If no specific MIME type can be indicated, then the type `application/octet-stream` is to be used.
|source a|
Optional attribute indicating the source of the meta data as a URI (cf. RFC 3986).
The base URI for the resolution of relative URIs is determined by the sourceBase attribute.

If the source attribute is missing, the meta data *MUST* be provided inline as contents of a Content element, which *MUST NOT* be present otherwise.
|sourceBase a|
Defines the base the source URI is resolved against:

If the attribute is missing or is specified as `file`, the source is resolved against the URI of the containing file.

If the containing model element has a source attribute, the sourceBase attribute can be specified as `resource`.
In this case the URI is resolved against the (resolved) source URI of the containing model element.

The last option allows the specification of meta data sources that reside inside a resource (for example an FMU) through relative URIs.
|===

===== Content

image:images/SystemStructureCommon_Content.svg[image]

This element specifies the inlined content of the model element meta data.

When this element is present, its contents *MUST* be an `srmd:SimulationResourceMetaData` element as specified by the SRMD schema of the SSP Traceability Specification, if the type attribute of the enclosing MetaData element is `application/x-srmd-meta-data`, or any other valid XML content if the type attribute references another MIME type.
In that case there *SHOULD* be a layered specification that defines how embedding the content works for that MIME type.

[#ssc_signature]
==== Signature Sequence

image:images/SystemStructureCommon_GSignature.svg[image]

The group GSignature allows the specification of digital signatures for a given model element.
Multiple (or no) Signature elements may be present in a given model element.

[width="100%",cols="33%,67%",options="header",]
|===
|Element   |Description
|Signature |One or more instances of this element *CAN* be present to specify signatures related to the containing model element.
See below for details.
|===

===== Signature

image:images/SystemStructureCommon_Signature.svg[image]

This element specifies digital signature information on the data or meta data referenced by the enclosing element:
If the Signature element is contained within a MetaData element, it refers to the meta data referenced by the MetaData element.
If the Signature element is contained within any other element, it refers to the content of that element.

The Signature element is structured by the following subordinated elements.

[width="100%",cols="33%,67%",options="header",]
|===
|Element  |Description
|Content  |An instance of this element *CAN* be present to contain inlined content of the signature.
If it is present, then the attribute `source` of the Signature element *MUST NOT* be present.
See below for details.
|===

The following XML attributes are specified for the Signature element:

[width="100%",cols="28%,72%",options="header",]
|===
|Attribute |Description
|role a|
This mandatory attribute specifies the role this signature has in the overall process.
It indicates whether the digital signature is intended to just convey the authenticity of the information (value `authenticity`), or whether a claim for suitability of the information for certain purposes is made (value `suitability`).
In the latter case, the digital signature format should include detailed information about what suitability claims are being made.
|type a|
This mandatory attribute specifies the MIME type of the signature, which does not have a default value.
If no specific MIME type can be indicated, then the type `application/octet-stream` is to be used.
|source a|
Optional attribute indicating the source of the signature as a URI (cf. RFC 3986).
The base URI for the resolution of relative URIs is determined by the sourceBase attribute.

If the source attribute is missing, the signature *MUST* be provided inline as contents of a Content element, which *MUST NOT* be present otherwise.
|sourceBase a|
Defines the base the source URI is resolved against:

If the attribute is missing or is specified as `file`, the source is resolved against the URI of the containing file.

If the containing model element has a source attribute, the sourceBase attribute can be specified as `resource`.
In this case the URI is resolved against the (resolved) source URI of the containing model element.

If the Signature element is contained within a MetaData element, the sourceBase attribute can be specified as `metaData`.
In this case the URI is resolved against the (resolved) URI of the meta data source.

The last two options allow the specification of signature sources that reside inside a resource (for example an FMU), or the meta data through relative URIs.
|===
